version: '3.3'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    ports:
      - '5432:5432'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local